# Generated by Django 6.1 on 2026-08-18 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataDomain',
            fields=[
                ('domain_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('logical_type', models.CharField(max_length=40)),
                ('python_type', models.CharField(max_length=40)),
                ('database_type', models.CharField(max_length=40)),
                ('length', models.PositiveIntegerField(blank=True, null=True)),
                ('precision', models.PositiveIntegerField(blank=True, null=True)),
                ('scale', models.PositiveIntegerField(blank=True, null=True)),
                ('value_nullable', models.BooleanField(default=False)),
                ('format_rule', models.CharField(blank=True, max_length=200)),
                ('minimum_value', models.CharField(blank=True, max_length=40)),
                ('maximum_value', models.CharField(blank=True, max_length=40)),
                ('allowed_values', models.JSONField(blank=True, default=list)),
                ('examples', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['domain_id'],
            },
        ),
        migrations.CreateModel(
            name='StandardWord',
            fields=[
                ('word_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('logical_word', models.CharField(max_length=100)),
                ('english_word', models.CharField(max_length=100)),
                ('approved_abbreviation', models.CharField(blank=True, max_length=30)),
                ('definition', models.TextField()),
                ('legacy_examples', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['word_id'],
            },
        ),
        migrations.CreateModel(
            name='StandardTerm',
            fields=[
                ('term_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('logical_term', models.CharField(max_length=100, unique=True)),
                ('physical_name', models.CharField(max_length=100, unique=True)),
                ('word_ids', models.CharField(max_length=200)),
                ('definition', models.TextField()),
                ('nullable', models.BooleanField(default=False)),
                ('source_columns', models.CharField(max_length=300)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='bookstore.datadomain')),
            ],
            options={
                'ordering': ['term_id'],
            },
        ),
    ]
