# Generated by Django 5.2.17 on 2026-08-26 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_book_bookorder_category_member_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField()),
                ('order_count_30d', models.PositiveIntegerField()),
                ('quantity_sum_30d', models.PositiveIntegerField()),
                ('spend_sum_30d', models.DecimalField(decimal_places=2, max_digits=12)),
                ('last_order_days_ago', models.PositiveIntegerField(blank=True, null=True)),
                ('source_file', models.CharField(max_length=200)),
                ('loaded_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.PROTECT, related_name='recommendation_features', to='bookstore.member')),
                ('preferred_category', models.ForeignKey(blank=True, db_column='preferred_category_code_30d', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preferred_by_features', to='bookstore.category')),
            ],
            options={
                'ordering': ['as_of_date', 'member_id'],
                'constraints': [models.UniqueConstraint(fields=('member', 'as_of_date'), name='uq_recommendation_feature_member_date')],
            },
        ),
    ]
