# Generated by Django 6.1 on 2026-08-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=10)),
                ('university', models.CharField(max_length=50)),
                ('line', models.CharField(max_length=10)),
                ('lesson', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('personnel', models.CharField(max_length=30)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('area', 'region', 'university', 'line', 'lesson', 'type', 'personnel'), name='unique_university_admission')],
            },
        ),
    ]
